// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.6.1
// source: lnurl.proto

package xlnrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	K1  string `protobuf:"bytes,1,opt,name=k1,proto3" json:"k1,omitempty"`
	Sig string `protobuf:"bytes,2,opt,name=sig,proto3" json:"sig,omitempty"`
	Key string `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *AuthRequest) Reset() {
	*x = AuthRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lnurl_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthRequest) ProtoMessage() {}

func (x *AuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lnurl_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthRequest.ProtoReflect.Descriptor instead.
func (*AuthRequest) Descriptor() ([]byte, []int) {
	return file_lnurl_proto_rawDescGZIP(), []int{0}
}

func (x *AuthRequest) GetK1() string {
	if x != nil {
		return x.K1
	}
	return ""
}

func (x *AuthRequest) GetSig() string {
	if x != nil {
		return x.Sig
	}
	return ""
}

func (x *AuthRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type LNURLResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Reason string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
}

func (x *LNURLResponse) Reset() {
	*x = LNURLResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lnurl_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LNURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LNURLResponse) ProtoMessage() {}

func (x *LNURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lnurl_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LNURLResponse.ProtoReflect.Descriptor instead.
func (*LNURLResponse) Descriptor() ([]byte, []int) {
	return file_lnurl_proto_rawDescGZIP(), []int{1}
}

func (x *LNURLResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *LNURLResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type RequestWithdrawRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	K1 string `protobuf:"bytes,1,opt,name=k1,proto3" json:"k1,omitempty"`
}

func (x *RequestWithdrawRequest) Reset() {
	*x = RequestWithdrawRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lnurl_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestWithdrawRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestWithdrawRequest) ProtoMessage() {}

func (x *RequestWithdrawRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lnurl_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestWithdrawRequest.ProtoReflect.Descriptor instead.
func (*RequestWithdrawRequest) Descriptor() ([]byte, []int) {
	return file_lnurl_proto_rawDescGZIP(), []int{2}
}

func (x *RequestWithdrawRequest) GetK1() string {
	if x != nil {
		return x.K1
	}
	return ""
}

type RequestWithdrawResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status             string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Reason             string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	Tag                string `protobuf:"bytes,3,opt,name=tag,proto3" json:"tag,omitempty"`
	Callback           string `protobuf:"bytes,4,opt,name=callback,proto3" json:"callback,omitempty"`
	K1                 string `protobuf:"bytes,5,opt,name=k1,proto3" json:"k1,omitempty"`
	DefaultDescription string `protobuf:"bytes,6,opt,name=defaultDescription,proto3" json:"defaultDescription,omitempty"`
	MinWithdrawable    uint64 `protobuf:"varint,7,opt,name=minWithdrawable,proto3" json:"minWithdrawable,omitempty"`
	MaxWithdrawable    uint64 `protobuf:"varint,8,opt,name=maxWithdrawable,proto3" json:"maxWithdrawable,omitempty"`
}

func (x *RequestWithdrawResponse) Reset() {
	*x = RequestWithdrawResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lnurl_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestWithdrawResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestWithdrawResponse) ProtoMessage() {}

func (x *RequestWithdrawResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lnurl_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestWithdrawResponse.ProtoReflect.Descriptor instead.
func (*RequestWithdrawResponse) Descriptor() ([]byte, []int) {
	return file_lnurl_proto_rawDescGZIP(), []int{3}
}

func (x *RequestWithdrawResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RequestWithdrawResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *RequestWithdrawResponse) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *RequestWithdrawResponse) GetCallback() string {
	if x != nil {
		return x.Callback
	}
	return ""
}

func (x *RequestWithdrawResponse) GetK1() string {
	if x != nil {
		return x.K1
	}
	return ""
}

func (x *RequestWithdrawResponse) GetDefaultDescription() string {
	if x != nil {
		return x.DefaultDescription
	}
	return ""
}

func (x *RequestWithdrawResponse) GetMinWithdrawable() uint64 {
	if x != nil {
		return x.MinWithdrawable
	}
	return 0
}

func (x *RequestWithdrawResponse) GetMaxWithdrawable() uint64 {
	if x != nil {
		return x.MaxWithdrawable
	}
	return 0
}

type WithdrawRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	K1 string `protobuf:"bytes,1,opt,name=k1,proto3" json:"k1,omitempty"`
	Pr string `protobuf:"bytes,2,opt,name=pr,proto3" json:"pr,omitempty"`
}

func (x *WithdrawRequest) Reset() {
	*x = WithdrawRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lnurl_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WithdrawRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithdrawRequest) ProtoMessage() {}

func (x *WithdrawRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lnurl_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithdrawRequest.ProtoReflect.Descriptor instead.
func (*WithdrawRequest) Descriptor() ([]byte, []int) {
	return file_lnurl_proto_rawDescGZIP(), []int{4}
}

func (x *WithdrawRequest) GetK1() string {
	if x != nil {
		return x.K1
	}
	return ""
}

func (x *WithdrawRequest) GetPr() string {
	if x != nil {
		return x.Pr
	}
	return ""
}

var File_lnurl_proto protoreflect.FileDescriptor

var file_lnurl_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x6c, 0x6e, 0x75, 0x72, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x78,
	0x6c, 0x6e, 0x72, 0x70, 0x63, 0x22, 0x41, 0x0a, 0x0b, 0x41, 0x75, 0x74, 0x68, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x6b, 0x31, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x6b, 0x31, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x69, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x73, 0x69, 0x67, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x3f, 0x0a, 0x0d, 0x4c, 0x4e, 0x55, 0x52,
	0x4c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x22, 0x28, 0x0a, 0x16, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x57, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x6b, 0x31, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x6b, 0x31, 0x22, 0x8b, 0x02, 0x0a, 0x17, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x57,
	0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f,
	0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12,
	0x10, 0x0a, 0x03, 0x74, 0x61, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x74, 0x61,
	0x67, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x12, 0x0e, 0x0a,
	0x02, 0x6b, 0x31, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x6b, 0x31, 0x12, 0x2e, 0x0a,
	0x12, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x12, 0x64, 0x65, 0x66, 0x61, 0x75,
	0x6c, 0x74, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x28, 0x0a,
	0x0f, 0x6d, 0x69, 0x6e, 0x57, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x61, 0x62, 0x6c, 0x65,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0f, 0x6d, 0x69, 0x6e, 0x57, 0x69, 0x74, 0x68, 0x64,
	0x72, 0x61, 0x77, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x28, 0x0a, 0x0f, 0x6d, 0x61, 0x78, 0x57, 0x69,
	0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x0f, 0x6d, 0x61, 0x78, 0x57, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x61, 0x62, 0x6c,
	0x65, 0x22, 0x31, 0x0a, 0x0f, 0x57, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x6b, 0x31, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x6b, 0x31, 0x12, 0x0e, 0x0a, 0x02, 0x70, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x70, 0x72, 0x32, 0xcb, 0x01, 0x0a, 0x05, 0x4c, 0x4e, 0x55, 0x52, 0x4c, 0x12, 0x32,
	0x0a, 0x04, 0x41, 0x75, 0x74, 0x68, 0x12, 0x13, 0x2e, 0x78, 0x6c, 0x6e, 0x72, 0x70, 0x63, 0x2e,
	0x41, 0x75, 0x74, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x78, 0x6c,
	0x6e, 0x72, 0x70, 0x63, 0x2e, 0x4c, 0x4e, 0x55, 0x52, 0x4c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x52, 0x0a, 0x0f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x57, 0x69, 0x74,
	0x68, 0x64, 0x72, 0x61, 0x77, 0x12, 0x1e, 0x2e, 0x78, 0x6c, 0x6e, 0x72, 0x70, 0x63, 0x2e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x57, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x78, 0x6c, 0x6e, 0x72, 0x70, 0x63, 0x2e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x57, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3a, 0x0a, 0x08, 0x57, 0x69, 0x74, 0x68, 0x64, 0x72,
	0x61, 0x77, 0x12, 0x17, 0x2e, 0x78, 0x6c, 0x6e, 0x72, 0x70, 0x63, 0x2e, 0x57, 0x69, 0x74, 0x68,
	0x64, 0x72, 0x61, 0x77, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x78, 0x6c,
	0x6e, 0x72, 0x70, 0x63, 0x2e, 0x4c, 0x4e, 0x55, 0x52, 0x4c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x42, 0x1f, 0x5a, 0x1d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x78, 0x62, 0x69, 0x74, 0x2d, 0x67, 0x67, 0x2f, 0x78, 0x6c, 0x6e, 0x2f, 0x78, 0x6c, 0x6e,
	0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_lnurl_proto_rawDescOnce sync.Once
	file_lnurl_proto_rawDescData = file_lnurl_proto_rawDesc
)

func file_lnurl_proto_rawDescGZIP() []byte {
	file_lnurl_proto_rawDescOnce.Do(func() {
		file_lnurl_proto_rawDescData = protoimpl.X.CompressGZIP(file_lnurl_proto_rawDescData)
	})
	return file_lnurl_proto_rawDescData
}

var file_lnurl_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_lnurl_proto_goTypes = []interface{}{
	(*AuthRequest)(nil),             // 0: xlnrpc.AuthRequest
	(*LNURLResponse)(nil),           // 1: xlnrpc.LNURLResponse
	(*RequestWithdrawRequest)(nil),  // 2: xlnrpc.RequestWithdrawRequest
	(*RequestWithdrawResponse)(nil), // 3: xlnrpc.RequestWithdrawResponse
	(*WithdrawRequest)(nil),         // 4: xlnrpc.WithdrawRequest
}
var file_lnurl_proto_depIdxs = []int32{
	0, // 0: xlnrpc.LNURL.Auth:input_type -> xlnrpc.AuthRequest
	2, // 1: xlnrpc.LNURL.RequestWithdraw:input_type -> xlnrpc.RequestWithdrawRequest
	4, // 2: xlnrpc.LNURL.Withdraw:input_type -> xlnrpc.WithdrawRequest
	1, // 3: xlnrpc.LNURL.Auth:output_type -> xlnrpc.LNURLResponse
	3, // 4: xlnrpc.LNURL.RequestWithdraw:output_type -> xlnrpc.RequestWithdrawResponse
	1, // 5: xlnrpc.LNURL.Withdraw:output_type -> xlnrpc.LNURLResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_lnurl_proto_init() }
func file_lnurl_proto_init() {
	if File_lnurl_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_lnurl_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lnurl_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LNURLResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lnurl_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestWithdrawRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lnurl_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestWithdrawResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lnurl_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WithdrawRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_lnurl_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_lnurl_proto_goTypes,
		DependencyIndexes: file_lnurl_proto_depIdxs,
		MessageInfos:      file_lnurl_proto_msgTypes,
	}.Build()
	File_lnurl_proto = out.File
	file_lnurl_proto_rawDesc = nil
	file_lnurl_proto_goTypes = nil
	file_lnurl_proto_depIdxs = nil
}
